defaults.url=https://sentry.io/
defaults.org=alm-group
defaults.project=react-native
# auth.token=REMPLACE_PAR_TON_AUTH_TOKEN
# Créer un token sur : https://alm-group.sentry.io/settings/auth-tokens/
# Scope requis : project:write
