import { StyleSheet, Platform } from 'react-native';
import { C } from '../config/constants';

export const styles = StyleSheet.create({
  safe:         { flex: 1, backgroundColor: C.bg },
  screen:       { flex: 1, backgroundColor: C.bg },
  screenTitle:  { fontSize: 24, fontWeight: '900', color: C.t1, letterSpacing: -0.8, marginBottom: 4 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: C.t1, letterSpacing: 0.5, marginBottom: 10 },
  header:       { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 8, paddingBottom: 8 },
  headerSub:    { fontSize: 14, color: C.t3, fontWeight: '500' },
  headerTitle:  { fontSize: 30, fontWeight: '900', color: C.t1, letterSpacing: -1 },
  headerIconBtn:{ width: 40, height: 40, borderRadius: 20, backgroundColor: C.card,
                  alignItems: 'center', justifyContent: 'center',
                  shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: .08, shadowRadius: 6 },
  heroCard:     { marginHorizontal: 16, marginBottom: 12, borderRadius: 24,
                  backgroundColor: C.mint, overflow: 'hidden', minHeight: 190 },
  heroTitle:    { fontSize: 28, fontWeight: '900', color: C.t1, lineHeight: 34, letterSpacing: -0.8, marginBottom: 16 },
  heroBtn:      { backgroundColor: '#fff', alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 10,
                  borderRadius: 100, shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
                  shadowOpacity: .08, shadowRadius: 6 },
  card:         { backgroundColor: C.card, borderRadius: 20, marginHorizontal: 16,
                  shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: .07, shadowRadius: 10 },
  productRow:   { flexDirection: 'row', alignItems: 'center', padding: 14 },
  rowBorder:    { borderBottomWidth: 1, borderBottomColor: C.border },
  productName:  { fontSize: 14, fontWeight: '700', color: C.t1, marginBottom: 2 },
  productSub:   { fontSize: 12, color: C.t3 },
  urgBadge:     { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  urgText:      { color: '#fff', fontSize: 12, fontWeight: '700' },
  tabBar:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around',
                  backgroundColor: '#fff', paddingVertical: 8, paddingBottom: Platform.OS === 'ios' ? 20 : 8,
                  borderTopWidth: 1, borderTopColor: C.border },
  tabItem:      { alignItems: 'center', gap: 2, paddingHorizontal: 14 },
  tabLabel:     { fontSize: 10, color: C.t4 },
  tabLabelActive: { fontSize: 10, fontWeight: '700', color: C.green },
  tabDot:       { width: 5, height: 5, borderRadius: 3, backgroundColor: C.green, marginTop: 1 },
  scanBtn:      { width: 56, height: 56, borderRadius: 28, backgroundColor: C.green,
                  alignItems: 'center', justifyContent: 'center',
                  shadowColor: C.green, shadowOffset: { width: 0, height: 4 }, shadowOpacity: .45, shadowRadius: 12,
                  marginBottom: Platform.OS === 'ios' ? 4 : 0 },
  badge:        { position: 'absolute', top: -2, right: -2, minWidth: 18, height: 18, borderRadius: 9,
                  backgroundColor: C.red, alignItems: 'center', justifyContent: 'center',
                  borderWidth: 2, borderColor: '#fff', paddingHorizontal: 3 },
  locTab:       { flex: 1, alignItems: 'center', padding: 12, borderRadius: 16, backgroundColor: 'rgba(0,0,0,0.04)' },
  locTabActive: { backgroundColor: C.card, shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
                  shadowOpacity: .06, shadowRadius: 6 },
  locTabLabel:  { fontSize: 11, color: C.t3, marginTop: 2 },
  searchBar:    { flexDirection: 'row', alignItems: 'center', padding: 11, borderRadius: 14,
                  backgroundColor: C.card, borderWidth: 1, borderColor: C.border, marginBottom: 12 },
  fridgeRow:    { flexDirection: 'row', alignItems: 'center', padding: 13, backgroundColor: C.card,
                  borderRadius: 18, shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
                  shadowOpacity: .06, shadowRadius: 8 },
  greenBtn:     { backgroundColor: C.green, padding: 15, borderRadius: 16, alignItems: 'center',
                  shadowColor: C.green, shadowOffset: { width: 0, height: 4 }, shadowOpacity: .35, shadowRadius: 12 },
  closeBtn:     { width: 38, height: 38, borderRadius: 12, backgroundColor: C.card,
                  alignItems: 'center', justifyContent: 'center',
                  borderWidth: 1, borderColor: C.border },
});
