/**
 * DEV-ONLY — dataset de démonstration pour comparer visuellement Mon Stock
 * au Master Screen. N'existe qu'en local :
 *  - jamais écrit dans Supabase (ids factices, aucun insert/update réel)
 *  - jamais actif en production (gardé par `__DEV__`, toujours false en build release)
 *  - jamais de migration, jamais de modification du compte réel
 *
 * Base 7 items (2/3/2) volontairement identique au Master pour neutraliser le
 * biais de volume — Priority/Soon restent strictement inchangés. Les lots de
 * primitives Food Language (LOT 01, LOT 02, LOTS 03-11) sont ajoutés
 * exclusivement en "Plus tard" pour audit visuel, sans perturber la
 * calibration Priority/Soon déjà validée. Raison de test explicite : revue
 * perceptuelle par lot vs Golden Set.
 *
 * Pour désactiver : mettre DEV_PREVIEW_STOCK_ENABLED à false, ou supprimer ce
 * fichier + son usage dans FridgeScreen.js.
 */

export const DEV_PREVIEW_STOCK_ENABLED = true;

function frDate(offsetDays) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`;
}

export function getDevPreviewItems() {
  const mk = (over) => ({
    family_id: '__dev_preview__',
    consumed: false,
    wasted: false,
    opened: false,
    location: 'Frigo',
    quantity: 1,
    total_units: 1,
    unit: '',
    category: '',
    brand: '',
    img_url: null,
    nutri_grade: null,
    price: null,
    ...over,
    id: `preview-${over.name}`,
  });

  return [
    // À utiliser en priorité — 2
    // localImage : primitive canonique Food Language validée. localImageRatio =
    // largeur/hauteur réelle du fichier — métadonnée générique de l'asset, jamais
    // un nom/id d'aliment, utilisée par InventoryProductRow pour la catégorie
    // morphologique "vertical étroit" (voir composant).
    mk({ name: 'Tomates cerises', emoji: '🍅', dlc: frDate(0), days_left: 0, localImage: require('../../assets/dev-preview-food/tomates-cerises.png'), localImageRatio: 834 / 587 }),
    mk({ name: 'Poulet rôti',     emoji: '🍗', dlc: frDate(0), days_left: 0, localImage: require('../../assets/dev-preview-food/poulet-roti.png'), localImageRatio: 979 / 745 }),
    // À utiliser prochainement — 3
    mk({ name: 'Yaourt nature',   emoji: '🥛', dlc: frDate(1), days_left: 1, localImage: require('../../assets/dev-preview-food/yaourt-nature.png'), localImageRatio: 270 / 248 }),
    mk({ name: 'Avocat',          emoji: '🥑', dlc: frDate(3), days_left: 3, localImage: require('../../assets/dev-preview-food/avocat.png'), localImageRatio: 497 / 717 }),
    mk({ name: 'Courgette',       emoji: '🥒', dlc: frDate(4), days_left: 4, localImage: require('../../assets/dev-preview-food/courgette.png'), localImageRatio: 1.5 }),
    // Plus tard — 2 (Master) + LOT 01 (11 primitives, audit visuel uniquement)
    mk({ name: 'Lait entier',     emoji: '🥛', dlc: frDate(7),  days_left: 7,  localImage: require('../../assets/dev-preview-food/lait-entier.png'), localImageRatio: 265 / 719 }),
    mk({ name: 'Fromage râpé',    emoji: '🧀', dlc: frDate(9),  days_left: 9, localImage: require('../../assets/dev-preview-food/fromage-rape-emmental.png'), localImageRatio: 1.7366 }),
    mk({ name: 'Crème fraîche',   emoji: '🥣', dlc: frDate(10), days_left: 10, localImage: require('../../assets/dev-preview-food/creme-fraiche.png'), localImageRatio: 321 / 242 }),
    mk({ name: 'Mozzarella',      emoji: '🧀', dlc: frDate(11), days_left: 11, localImage: require('../../assets/dev-preview-food/mozzarella.png'), localImageRatio: 302 / 255 }),
    mk({ name: 'Jambon',          emoji: '🍖', dlc: frDate(12), days_left: 12, localImage: require('../../assets/dev-preview-food/jambon.png'), localImageRatio: 364 / 227 }),
    mk({ name: 'Lardons',         emoji: '🥓', dlc: frDate(13), days_left: 13, localImage: require('../../assets/dev-preview-food/lardons.png'), localImageRatio: 339 / 235 }),
    mk({ name: 'Saucisses',       emoji: '🌭', dlc: frDate(14), days_left: 14, localImage: require('../../assets/dev-preview-food/saucisses.png'), localImageRatio: 354 / 264 }),
    mk({ name: 'Steak haché',     emoji: '🥩', dlc: frDate(15), days_left: 15, localImage: require('../../assets/dev-preview-food/steak-hache.png'), localImageRatio: 350 / 254 }),
    mk({ name: 'Poulet cru',      emoji: '🍗', dlc: frDate(16), days_left: 16, localImage: require('../../assets/dev-preview-food/poulet-cru.png'), localImageRatio: 364 / 261 }),
    mk({ name: 'Saumon',          emoji: '🐟', dlc: frDate(17), days_left: 17, localImage: require('../../assets/dev-preview-food/saumon.png'), localImageRatio: 353 / 241 }),
    mk({ name: 'Poisson blanc',   emoji: '🐟', dlc: frDate(18), days_left: 18, localImage: require('../../assets/dev-preview-food/poisson-blanc.png'), localImageRatio: 363 / 225 }),
    mk({ name: 'Champignons',     emoji: '🍄', dlc: frDate(19), days_left: 19, localImage: require('../../assets/dev-preview-food/champignons.png'), localImageRatio: 358 / 257 }),
    mk({ name: 'Salade',          emoji: '🥬', dlc: frDate(20), days_left: 20, localImage: require('../../assets/dev-preview-food/salade.png'), localImageRatio: 364 / 261 }),
    // LOT 02 (12 primitives, audit visuel uniquement)
    mk({ name: 'Œufs',            emoji: '🥚', dlc: frDate(21), days_left: 21, localImage: require('../../assets/dev-preview-food/oeufs.png'), localImageRatio: 310 / 178 }),
    mk({ name: 'Beurre',          emoji: '🧈', dlc: frDate(22), days_left: 22, localImage: require('../../assets/dev-preview-food/beurre.png'), localImageRatio: 295 / 190 }),
    mk({ name: 'Emmental',        emoji: '🧀', dlc: frDate(23), days_left: 23, localImage: require('../../assets/dev-preview-food/emmental.png'), localImageRatio: 283 / 183 }),
    mk({ name: 'Camembert',       emoji: '🧀', dlc: frDate(24), days_left: 24, localImage: require('../../assets/dev-preview-food/camembert.png'), localImageRatio: 283 / 164 }),
    mk({ name: 'Chèvre',          emoji: '🧀', dlc: frDate(25), days_left: 25, localImage: require('../../assets/dev-preview-food/chevre.png'), localImageRatio: 227 / 175 }),
    mk({ name: 'Bacon',           emoji: '🥓', dlc: frDate(26), days_left: 26, localImage: require('../../assets/dev-preview-food/bacon.png'), localImageRatio: 355 / 169 }),
    mk({ name: 'Dinde',           emoji: '🍖', dlc: frDate(27), days_left: 27, localImage: require('../../assets/dev-preview-food/dinde.png'), localImageRatio: 321 / 161 }),
    mk({ name: 'Viande hachée',   emoji: '🥩', dlc: frDate(28), days_left: 28, localImage: require('../../assets/dev-preview-food/viande-hachee.png'), localImageRatio: 302 / 152 }),
    mk({ name: 'Crevettes',       emoji: '🦐', dlc: frDate(29), days_left: 29, localImage: require('../../assets/dev-preview-food/crevettes.png'), localImageRatio: 286 / 157 }),
    mk({ name: 'Carottes',        emoji: '🥕', dlc: frDate(30), days_left: 30, localImage: require('../../assets/dev-preview-food/carottes.png'), localImageRatio: 331 / 186 }),
    mk({ name: 'Poivron rouge',   emoji: '🫑', dlc: frDate(31), days_left: 31, localImage: require('../../assets/dev-preview-food/poivron-rouge.png'), localImageRatio: 182 / 195 }),
    mk({ name: 'Brocoli',         emoji: '🥦', dlc: frDate(32), days_left: 32, localImage: require('../../assets/dev-preview-food/brocoli.png'), localImageRatio: 301 / 199 }),
    // LOTS 03-11 (95 primitives, audit visuel uniquement)
    mk({ name: 'Citron',          emoji: '🍋', dlc: frDate(33), days_left: 33, localImage: require('../../assets/dev-preview-food/citron.png'), localImageRatio: 1.4796 }),
    mk({ name: 'Citron vert',     emoji: '🍈', dlc: frDate(34), days_left: 34, localImage: require('../../assets/dev-preview-food/citron-vert.png'), localImageRatio: 1.4844 }),
    mk({ name: 'Orange',          emoji: '🍊', dlc: frDate(35), days_left: 35, localImage: require('../../assets/dev-preview-food/orange.png'), localImageRatio: 1.3731 }),
    mk({ name: 'Pomme',           emoji: '🍎', dlc: frDate(36), days_left: 36, localImage: require('../../assets/dev-preview-food/pomme.png'), localImageRatio: 1.3586 }),
    mk({ name: 'Poire',           emoji: '🍐', dlc: frDate(37), days_left: 37, localImage: require('../../assets/dev-preview-food/poire.png'), localImageRatio: 1.1376 }),
    mk({ name: 'Raisins',         emoji: '🍇', dlc: frDate(38), days_left: 38, localImage: require('../../assets/dev-preview-food/raisins.png'), localImageRatio: 1.6758 }),
    mk({ name: 'Myrtilles',       emoji: '🫐', dlc: frDate(39), days_left: 39, localImage: require('../../assets/dev-preview-food/myrtilles.png'), localImageRatio: 1.8295 }),
    mk({ name: 'Pâtes',           emoji: '🍝', dlc: frDate(40), days_left: 40, localImage: require('../../assets/dev-preview-food/pates.png'), localImageRatio: 1.7969 }),
    mk({ name: 'Riz',             emoji: '🍚', dlc: frDate(41), days_left: 41, localImage: require('../../assets/dev-preview-food/riz.png'), localImageRatio: 2.54 }),
    mk({ name: 'Pommes de terre', emoji: '🥔', dlc: frDate(42), days_left: 42, localImage: require('../../assets/dev-preview-food/pommes-de-terre.png'), localImageRatio: 1.6685 }),
    mk({ name: 'Oignon',          emoji: '🧅', dlc: frDate(43), days_left: 43, localImage: require('../../assets/dev-preview-food/oignon.png'), localImageRatio: 1.65 }),
    mk({ name: 'Ail',             emoji: '🧄', dlc: frDate(44), days_left: 44, localImage: require('../../assets/dev-preview-food/ail.png'), localImageRatio: 1.6786 }),
    mk({ name: 'Farine',          emoji: '🌾', dlc: frDate(45), days_left: 45, localImage: require('../../assets/dev-preview-food/farine.png'), localImageRatio: 1.3317 }),
    mk({ name: 'Sucre',           emoji: '🍬', dlc: frDate(46), days_left: 46, localImage: require('../../assets/dev-preview-food/sucre.png'), localImageRatio: 1.2864 }),
    mk({ name: 'Lentilles',       emoji: '🫘', dlc: frDate(47), days_left: 47, localImage: require('../../assets/dev-preview-food/lentilles.png'), localImageRatio: 1.7802 }),
    mk({ name: 'Pois chiches',    emoji: '🫘', dlc: frDate(48), days_left: 48, localImage: require('../../assets/dev-preview-food/pois-chiches.png'), localImageRatio: 1.5234 }),
    mk({ name: 'Haricots rouges', emoji: '🫘', dlc: frDate(49), days_left: 49, localImage: require('../../assets/dev-preview-food/haricots-rouges.png'), localImageRatio: 1.7692 }),
    mk({ name: 'Thon en conserve',emoji: '🥫', dlc: frDate(50), days_left: 50, localImage: require('../../assets/dev-preview-food/thon-en-conserve.png'), localImageRatio: 1.5089 }),
    mk({ name: 'Concentré de tomates', emoji: '🥫', dlc: frDate(51), days_left: 51, localImage: require('../../assets/dev-preview-food/concentre-de-tomates.png'), localImageRatio: 1.3427 }),
    mk({ name: "Huile d'olive",   emoji: '🫒', dlc: frDate(52), days_left: 52, localImage: require('../../assets/dev-preview-food/huile-d-olive.png'), localImageRatio: 1.3065 }),
    mk({ name: 'Miel',            emoji: '🍯', dlc: frDate(53), days_left: 53, localImage: require('../../assets/dev-preview-food/miel.png'), localImageRatio: 1.2015 }),
    mk({ name: 'Cornichons',      emoji: '🥒', dlc: frDate(54), days_left: 54, localImage: require('../../assets/dev-preview-food/cornichons.png'), localImageRatio: 1.5852 }),
    mk({ name: 'Échalote',        emoji: '🧅', dlc: frDate(55), days_left: 55, localImage: require('../../assets/dev-preview-food/echalote.png'), localImageRatio: 1.3518 }),
    mk({ name: 'Gingembre',       emoji: '🫚', dlc: frDate(56), days_left: 56, localImage: require('../../assets/dev-preview-food/gingembre.png'), localImageRatio: 1.3766 }),
    mk({ name: 'Patate douce',    emoji: '🍠', dlc: frDate(57), days_left: 57, localImage: require('../../assets/dev-preview-food/patate-douce.png'), localImageRatio: 1.476 }),
    mk({ name: 'Courge butternut',emoji: '🎃', dlc: frDate(58), days_left: 58, localImage: require('../../assets/dev-preview-food/courge-butternut.png'), localImageRatio: 1.2 }),
    mk({ name: 'Concombre',       emoji: '🥒', dlc: frDate(60), days_left: 60, localImage: require('../../assets/dev-preview-food/concombre.png'), localImageRatio: 1.4615 }),
    mk({ name: 'Aubergine',       emoji: '🍆', dlc: frDate(61), days_left: 61, localImage: require('../../assets/dev-preview-food/aubergine.png'), localImageRatio: 2.0178 }),
    mk({ name: 'Tomate',          emoji: '🍅', dlc: frDate(62), days_left: 62, localImage: require('../../assets/dev-preview-food/tomate.png'), localImageRatio: 1.0759 }),
    mk({ name: 'Mayonnaise',      emoji: '🥫', dlc: frDate(63), days_left: 63, localImage: require('../../assets/dev-preview-food/mayonnaise.png'), localImageRatio: 1.1888 }),
    mk({ name: 'Ketchup',         emoji: '🍅', dlc: frDate(64), days_left: 64, localImage: require('../../assets/dev-preview-food/ketchup.png'), localImageRatio: 1.208 }),
    mk({ name: 'Moutarde',        emoji: '🌭', dlc: frDate(65), days_left: 65, localImage: require('../../assets/dev-preview-food/moutarde.png'), localImageRatio: 1.2008 }),
    mk({ name: 'Sauce blanche',   emoji: '🥣', dlc: frDate(66), days_left: 66, localImage: require('../../assets/dev-preview-food/sauce-blanche.png'), localImageRatio: 1.1781 }),
    mk({ name: 'Yaourt aromatisé',emoji: '🥛', dlc: frDate(67), days_left: 67, localImage: require('../../assets/dev-preview-food/yaourt-aromatise.png'), localImageRatio: 1.1278 }),
    mk({ name: 'Fromage blanc',   emoji: '🥣', dlc: frDate(68), days_left: 68, localImage: require('../../assets/dev-preview-food/fromage-blanc.png'), localImageRatio: 1.1746 }),
    mk({ name: 'Fromage frais',   emoji: '🧀', dlc: frDate(69), days_left: 69, localImage: require('../../assets/dev-preview-food/fromage-frais.png'), localImageRatio: 1.4058 }),
    mk({ name: 'Pesto',           emoji: '🌿', dlc: frDate(70), days_left: 70, localImage: require('../../assets/dev-preview-food/pesto.png'), localImageRatio: 1.1587 }),
    mk({ name: 'Jus de citron',   emoji: '🍋', dlc: frDate(71), days_left: 71, localImage: require('../../assets/dev-preview-food/jus-de-citron.png'), localImageRatio: 0.6145 }),
    mk({ name: 'Herbes fraîches', emoji: '🌿', dlc: frDate(72), days_left: 72, localImage: require('../../assets/dev-preview-food/herbes-fraiches.png'), localImageRatio: 1.5695 }),
    mk({ name: 'Olives vertes',   emoji: '🫒', dlc: frDate(73), days_left: 73, localImage: require('../../assets/dev-preview-food/olives-vertes.png'), localImageRatio: 1.1635 }),
    mk({ name: 'Jambon cru',      emoji: '🍖', dlc: frDate(74), days_left: 74, localImage: require('../../assets/dev-preview-food/jambon-cru.png'), localImageRatio: 1.5612 }),
    mk({ name: 'Salami',          emoji: '🍖', dlc: frDate(75), days_left: 75, localImage: require('../../assets/dev-preview-food/salami.png'), localImageRatio: 1.5818 }),
    mk({ name: 'Chorizo',         emoji: '🌭', dlc: frDate(76), days_left: 76, localImage: require('../../assets/dev-preview-food/chorizo.png'), localImageRatio: 1.6233 }),
    mk({ name: 'Pâté',            emoji: '🥫', dlc: frDate(77), days_left: 77, localImage: require('../../assets/dev-preview-food/pate.png'), localImageRatio: 1.4682 }),
    mk({ name: 'Rillettes',       emoji: '🥫', dlc: frDate(78), days_left: 78, localImage: require('../../assets/dev-preview-food/rillettes.png'), localImageRatio: 1.1728 }),
    mk({ name: 'Saumon fumé',     emoji: '🐟', dlc: frDate(79), days_left: 79, localImage: require('../../assets/dev-preview-food/saumon-fume.png'), localImageRatio: 1.515 }),
    mk({ name: 'Truite fumée',    emoji: '🐟', dlc: frDate(80), days_left: 80, localImage: require('../../assets/dev-preview-food/truite-fumee.png'), localImageRatio: 1.5419 }),
    mk({ name: 'Surimi',          emoji: '🦀', dlc: frDate(81), days_left: 81, localImage: require('../../assets/dev-preview-food/surimi.png'), localImageRatio: 1.3822 }),
    mk({ name: 'Tofu nature',     emoji: '🧊', dlc: frDate(82), days_left: 82, localImage: require('../../assets/dev-preview-food/tofu-nature.png'), localImageRatio: 1.2176 }),
    mk({ name: 'Feta',            emoji: '🧀', dlc: frDate(83), days_left: 83, localImage: require('../../assets/dev-preview-food/feta.png'), localImageRatio: 1.2049 }),
    mk({ name: 'Amandes',         emoji: '🌰', dlc: frDate(84), days_left: 84, localImage: require('../../assets/dev-preview-food/amandes.png'), localImageRatio: 1.6616 }),
    mk({ name: 'Noix',            emoji: '🌰', dlc: frDate(85), days_left: 85, localImage: require('../../assets/dev-preview-food/noix.png'), localImageRatio: 1.5953 }),
    mk({ name: 'Noisettes',       emoji: '🌰', dlc: frDate(86), days_left: 86, localImage: require('../../assets/dev-preview-food/noisettes.png'), localImageRatio: 1.5604 }),
    mk({ name: 'Noix de cajou',   emoji: '🌰', dlc: frDate(87), days_left: 87, localImage: require('../../assets/dev-preview-food/noix-de-cajou.png'), localImageRatio: 1.7817 }),
    mk({ name: 'Raisins secs',    emoji: '🍇', dlc: frDate(88), days_left: 88, localImage: require('../../assets/dev-preview-food/raisins-secs.png'), localImageRatio: 1.7135 }),
    mk({ name: 'Dattes',          emoji: '🌴', dlc: frDate(89), days_left: 89, localImage: require('../../assets/dev-preview-food/dattes.png'), localImageRatio: 1.5283 }),
    mk({ name: 'Cranberries séchées', emoji: '🍒', dlc: frDate(90), days_left: 90, localImage: require('../../assets/dev-preview-food/cranberries-sechees.png'), localImageRatio: 1.5544 }),
    mk({ name: 'Graines de chia', emoji: '🌱', dlc: frDate(91), days_left: 91, localImage: require('../../assets/dev-preview-food/graines-de-chia.png'), localImageRatio: 1.7978 }),
    mk({ name: 'Graines de lin',  emoji: '🌱', dlc: frDate(92), days_left: 92, localImage: require('../../assets/dev-preview-food/graines-de-lin.png'), localImageRatio: 1.7419 }),
    mk({ name: 'Graines de tournesol', emoji: '🌻', dlc: frDate(93), days_left: 93, localImage: require('../../assets/dev-preview-food/graines-de-tournesol.png'), localImageRatio: 1.7368 }),
    mk({ name: "Flocons d'avoine",emoji: '🌾', dlc: frDate(94), days_left: 94, localImage: require('../../assets/dev-preview-food/flocons-d-avoine.png'), localImageRatio: 1.7249 }),
    mk({ name: 'Muesli',          emoji: '🥣', dlc: frDate(95), days_left: 95, localImage: require('../../assets/dev-preview-food/muesli.png'), localImageRatio: 1.6381 }),
    mk({ name: 'Sel',             emoji: '🧂', dlc: frDate(96), days_left: 96, localImage: require('../../assets/dev-preview-food/sel.png'), localImageRatio: 1.5744 }),
    mk({ name: 'Poivre noir',     emoji: '⚫️', dlc: frDate(97), days_left: 97, localImage: require('../../assets/dev-preview-food/poivre-noir.png'), localImageRatio: 1.6492 }),
    mk({ name: 'Paprika',         emoji: '🌶️', dlc: frDate(98), days_left: 98, localImage: require('../../assets/dev-preview-food/paprika.png'), localImageRatio: 1.5122 }),
    mk({ name: 'Cumin moulu',     emoji: '🌿', dlc: frDate(99), days_left: 99, localImage: require('../../assets/dev-preview-food/cumin-moulu.png'), localImageRatio: 1.5833 }),
    mk({ name: 'Origan séché',    emoji: '🌿', dlc: frDate(100), days_left: 100, localImage: require('../../assets/dev-preview-food/origan-seche.png'), localImageRatio: 1.6615 }),
    mk({ name: 'Basilic séché',   emoji: '🌿', dlc: frDate(101), days_left: 101, localImage: require('../../assets/dev-preview-food/basilic-seche.png'), localImageRatio: 1.5427 }),
    mk({ name: 'Cannelle',        emoji: '🟤', dlc: frDate(102), days_left: 102, localImage: require('../../assets/dev-preview-food/cannelle.png'), localImageRatio: 1.3021 }),
    mk({ name: 'Curcuma',         emoji: '🟡', dlc: frDate(103), days_left: 103, localImage: require('../../assets/dev-preview-food/curcuma.png'), localImageRatio: 1.5459 }),
    mk({ name: 'Piment de Cayenne', emoji: '🌶️', dlc: frDate(104), days_left: 104, localImage: require('../../assets/dev-preview-food/piment-de-cayenne.png'), localImageRatio: 1.5404 }),
    mk({ name: 'Laurier',         emoji: '🌿', dlc: frDate(105), days_left: 105, localImage: require('../../assets/dev-preview-food/laurier.png'), localImageRatio: 1.7258 }),
    mk({ name: 'Thym séché',      emoji: '🌿', dlc: frDate(106), days_left: 106, localImage: require('../../assets/dev-preview-food/thym-seche.png'), localImageRatio: 1.6633 }),
    mk({ name: 'Romarin séché',   emoji: '🌿', dlc: frDate(107), days_left: 107, localImage: require('../../assets/dev-preview-food/romarin-seche.png'), localImageRatio: 1.7539 }),
    mk({ name: 'Yaourt grec',     emoji: '🥣', dlc: frDate(108), days_left: 108, localImage: require('../../assets/dev-preview-food/yaourt-grec.png'), localImageRatio: 1.1519 }),
    mk({ name: 'Yaourt aux fruits', emoji: '🍓', dlc: frDate(109), days_left: 109, localImage: require('../../assets/dev-preview-food/yaourt-aux-fruits.png'), localImageRatio: 1.1288 }),
    mk({ name: 'Fromage à tartiner', emoji: '🧀', dlc: frDate(110), days_left: 110, localImage: require('../../assets/dev-preview-food/fromage-a-tartiner.png'), localImageRatio: 1.3813 }),
    mk({ name: 'Crème liquide',   emoji: '🥛', dlc: frDate(111), days_left: 111, localImage: require('../../assets/dev-preview-food/creme-liquide.png'), localImageRatio: 0.8057 }),
    mk({ name: 'Rillettes de thon', emoji: '🐟', dlc: frDate(112), days_left: 112, localImage: require('../../assets/dev-preview-food/rillettes-de-thon.png'), localImageRatio: 1.1835 }),
    mk({ name: 'Œufs durs',       emoji: '🥚', dlc: frDate(113), days_left: 113, localImage: require('../../assets/dev-preview-food/oeufs-durs.png'), localImageRatio: 1.3347 }),
    mk({ name: 'Pâtes fraîches',  emoji: '🍝', dlc: frDate(114), days_left: 114, localImage: require('../../assets/dev-preview-food/pates-fraiches.png'), localImageRatio: 1.3975 }),
    mk({ name: 'Tofu soyeux',     emoji: '🧊', dlc: frDate(115), days_left: 115, localImage: require('../../assets/dev-preview-food/tofu-soyeux.png'), localImageRatio: 1.397 }),
    mk({ name: 'Houmous',         emoji: '🥣', dlc: frDate(116), days_left: 116, localImage: require('../../assets/dev-preview-food/houmous.png'), localImageRatio: 1.2 }),
    mk({ name: 'Soupe fraîche',   emoji: '🍲', dlc: frDate(117), days_left: 117, localImage: require('../../assets/dev-preview-food/soupe-fraiche.png'), localImageRatio: 1.104 }),
    mk({ name: 'Beurre demi-sel', emoji: '🧈', dlc: frDate(118), days_left: 118, localImage: require('../../assets/dev-preview-food/beurre-demi-sel.png'), localImageRatio: 1.3804 }),
    mk({ name: 'Fromage frais ail et fines herbes', emoji: '🧀', dlc: frDate(119), days_left: 119, localImage: require('../../assets/dev-preview-food/fromage-frais-ail-fines-herbes.png'), localImageRatio: 1.1638 }),
    mk({ name: 'Chocolat noir',   emoji: '🍫', dlc: frDate(120), days_left: 120, localImage: require('../../assets/dev-preview-food/chocolat-noir.png'), localImageRatio: 1.3598 }),
    mk({ name: 'Dessert chocolat', emoji: '🍫', dlc: frDate(121), days_left: 121, localImage: require('../../assets/dev-preview-food/dessert-chocolat.png'), localImageRatio: 1.015 }),
    mk({ name: 'Crème dessert vanille', emoji: '🍮', dlc: frDate(122), days_left: 122, localImage: require('../../assets/dev-preview-food/creme-dessert-vanille.png'), localImageRatio: 1.0276 }),
    mk({ name: 'Flan vanille',    emoji: '🍮', dlc: frDate(123), days_left: 123, localImage: require('../../assets/dev-preview-food/flan-vanille.png'), localImageRatio: 1.5892 }),
    mk({ name: 'Yaourt à boire',  emoji: '🥤', dlc: frDate(124), days_left: 124, localImage: require('../../assets/dev-preview-food/yaourt-a-boire.png'), localImageRatio: 0.613 }),
    mk({ name: "Jus d'orange frais", emoji: '🍊', dlc: frDate(125), days_left: 125, localImage: require('../../assets/dev-preview-food/jus-d-orange-frais.png'), localImageRatio: 0.8797 }),
    mk({ name: 'Salade verte',    emoji: '🥬', dlc: frDate(126), days_left: 126, localImage: require('../../assets/dev-preview-food/salade-verte.png'), localImageRatio: 1.225 }),
    mk({ name: 'Radis',           emoji: '🌱', dlc: frDate(127), days_left: 127, localImage: require('../../assets/dev-preview-food/radis.png'), localImageRatio: 1.3819 }),
    // LOTS 12-13 (22 primitives réellement nouvelles, audit visuel uniquement)
    mk({ name: 'Gruyère',         emoji: '🧀', dlc: frDate(128), days_left: 128, localImage: require('../../assets/dev-preview-food/gruyere.png'), localImageRatio: 1.4932 }),
    mk({ name: 'Parmesan',        emoji: '🧀', dlc: frDate(129), days_left: 129, localImage: require('../../assets/dev-preview-food/parmesan.png'), localImageRatio: 1.5922 }),
    mk({ name: 'Fromage râpé parmesan', emoji: '🧀', dlc: frDate(130), days_left: 130, localImage: require('../../assets/dev-preview-food/fromage-rape-parmesan.png'), localImageRatio: 1.6616 }),
    mk({ name: 'Mozzarella râpée',emoji: '🧀', dlc: frDate(131), days_left: 131, localImage: require('../../assets/dev-preview-food/mozzarella-rapee.png'), localImageRatio: 1.7192 }),
    mk({ name: 'Comté',           emoji: '🧀', dlc: frDate(132), days_left: 132, localImage: require('../../assets/dev-preview-food/comte.png'), localImageRatio: 1.5381 }),
    mk({ name: 'Mimolette',       emoji: '🧀', dlc: frDate(133), days_left: 133, localImage: require('../../assets/dev-preview-food/mimolette.png'), localImageRatio: 1.4509 }),
    mk({ name: 'Bleu',            emoji: '🧀', dlc: frDate(134), days_left: 134, localImage: require('../../assets/dev-preview-food/bleu.png'), localImageRatio: 1.5261 }),
    mk({ name: 'Chèvre frais',    emoji: '🧀', dlc: frDate(135), days_left: 135, localImage: require('../../assets/dev-preview-food/chevre-frais.png'), localImageRatio: 1.2811 }),
    mk({ name: 'Ricotta',         emoji: '🧀', dlc: frDate(136), days_left: 136, localImage: require('../../assets/dev-preview-food/ricotta.png'), localImageRatio: 1.253 }),
    mk({ name: 'Guacamole',       emoji: '🥑', dlc: frDate(137), days_left: 137, localImage: require('../../assets/dev-preview-food/guacamole.png'), localImageRatio: 1.124 }),
    mk({ name: 'Tzatziki',        emoji: '🥒', dlc: frDate(138), days_left: 138, localImage: require('../../assets/dev-preview-food/tzatziki.png'), localImageRatio: 1.0723 }),
    mk({ name: 'Taboulé',         emoji: '🌾', dlc: frDate(139), days_left: 139, localImage: require('../../assets/dev-preview-food/taboule.png'), localImageRatio: 1.0924 }),
    mk({ name: 'Carottes râpées', emoji: '🥕', dlc: frDate(140), days_left: 140, localImage: require('../../assets/dev-preview-food/carottes-rapees.png'), localImageRatio: 1.0875 }),
    mk({ name: 'Betteraves râpées', emoji: '🟣', dlc: frDate(141), days_left: 141, localImage: require('../../assets/dev-preview-food/betteraves-rapees.png'), localImageRatio: 1.1245 }),
    mk({ name: 'Concombre en rondelles', emoji: '🥒', dlc: frDate(142), days_left: 142, localImage: require('../../assets/dev-preview-food/concombre-en-rondelles.png'), localImageRatio: 1.1446 }),
    mk({ name: 'Œufs brouillés',  emoji: '🍳', dlc: frDate(143), days_left: 143, localImage: require('../../assets/dev-preview-food/oeufs-brouilles.png'), localImageRatio: 1.1673 }),
    mk({ name: 'Omelette nature', emoji: '🍳', dlc: frDate(144), days_left: 144, localImage: require('../../assets/dev-preview-food/omelette-nature.png'), localImageRatio: 1.5245 }),
    mk({ name: 'Riz cuit',        emoji: '🍚', dlc: frDate(145), days_left: 145, localImage: require('../../assets/dev-preview-food/riz-cuit.png'), localImageRatio: 1.1484 }),
    mk({ name: 'Quinoa cuit',     emoji: '🌾', dlc: frDate(146), days_left: 146, localImage: require('../../assets/dev-preview-food/quinoa-cuit.png'), localImageRatio: 1.1032 }),
    mk({ name: 'Lentilles cuites', emoji: '🫘', dlc: frDate(147), days_left: 147, localImage: require('../../assets/dev-preview-food/lentilles-cuites.png'), localImageRatio: 1.1067 }),
    mk({ name: 'Pâtes cuites',    emoji: '🍝', dlc: frDate(148), days_left: 148, localImage: require('../../assets/dev-preview-food/pates-cuites.png'), localImageRatio: 1.131 }),
    mk({ name: 'Purée de pommes de terre', emoji: '🥔', dlc: frDate(149), days_left: 149, localImage: require('../../assets/dev-preview-food/puree-pommes-de-terre.png'), localImageRatio: 1.1264 }),
    // LOTS 14-16 (46 primitives réellement nouvelles ou variantes utiles validées, audit visuel uniquement)
    mk({ name: 'Haricots verts',  emoji: '🫛', dlc: frDate(150), days_left: 150, localImage: require('../../assets/dev-preview-food/haricots-verts.png'), localImageRatio: 1.8535 }),
    mk({ name: 'Chou-fleur',      emoji: '🥦', dlc: frDate(151), days_left: 151, localImage: require('../../assets/dev-preview-food/chou-fleur.png'), localImageRatio: 1.255 }),
    mk({ name: 'Asperges vertes', emoji: '🌱', dlc: frDate(152), days_left: 152, localImage: require('../../assets/dev-preview-food/asperges-vertes.png'), localImageRatio: 1.7953 }),
    mk({ name: 'Épinards',        emoji: '🥬', dlc: frDate(153), days_left: 153, localImage: require('../../assets/dev-preview-food/epinards.png'), localImageRatio: 1.7186 }),
    mk({ name: 'Roquette',        emoji: '🥬', dlc: frDate(154), days_left: 154, localImage: require('../../assets/dev-preview-food/roquette.png'), localImageRatio: 1.6264 }),
    mk({ name: 'Endives',         emoji: '🥬', dlc: frDate(155), days_left: 155, localImage: require('../../assets/dev-preview-food/endives.png'), localImageRatio: 1.5085 }),
    mk({ name: 'Fenouil',         emoji: '🌿', dlc: frDate(156), days_left: 156, localImage: require('../../assets/dev-preview-food/fenouil.png'), localImageRatio: 1.0443 }),
    mk({ name: 'Oeufs de caille', emoji: '🥚', dlc: frDate(157), days_left: 157, localImage: require('../../assets/dev-preview-food/oeufs-de-caille.png'), localImageRatio: 1.5682 }),
    mk({ name: 'Basilic frais',   emoji: '🌿', dlc: frDate(158), days_left: 158, localImage: require('../../assets/dev-preview-food/basilic-frais.png'), localImageRatio: 1.4602 }),
    mk({ name: 'Persil frisé',    emoji: '🌿', dlc: frDate(159), days_left: 159, localImage: require('../../assets/dev-preview-food/persil-frise.png'), localImageRatio: 1.7485 }),
    mk({ name: 'Ciboulette',      emoji: '🌿', dlc: frDate(160), days_left: 160, localImage: require('../../assets/dev-preview-food/ciboulette.png'), localImageRatio: 1.9226 }),
    mk({ name: 'Oignons nouveaux', emoji: '🧅', dlc: frDate(161), days_left: 161, localImage: require('../../assets/dev-preview-food/oignons-nouveaux.png'), localImageRatio: 1.8247 }),
    mk({ name: 'Pois gourmands',  emoji: '🌱', dlc: frDate(162), days_left: 162, localImage: require('../../assets/dev-preview-food/pois-gourmands.png'), localImageRatio: 1.7877 }),
    mk({ name: 'Petits pois',     emoji: '🟢', dlc: frDate(163), days_left: 163, localImage: require('../../assets/dev-preview-food/petits-pois.png'), localImageRatio: 2.0161 }),
    mk({ name: 'Pain de mie',     emoji: '🍞', dlc: frDate(164), days_left: 164, localImage: require('../../assets/dev-preview-food/pain-de-mie.png'), localImageRatio: 1.4057 }),
    mk({ name: 'Baguette',        emoji: '🥖', dlc: frDate(165), days_left: 165, localImage: require('../../assets/dev-preview-food/baguette.png'), localImageRatio: 1.8225 }),
    mk({ name: 'Croissant',       emoji: '🥐', dlc: frDate(166), days_left: 166, localImage: require('../../assets/dev-preview-food/croissant.png'), localImageRatio: 1.655 }),
    mk({ name: 'Pain au chocolat', emoji: '🥐', dlc: frDate(167), days_left: 167, localImage: require('../../assets/dev-preview-food/pain-au-chocolat.png'), localImageRatio: 1.4576 }),
    mk({ name: 'Bagel',           emoji: '🥯', dlc: frDate(168), days_left: 168, localImage: require('../../assets/dev-preview-food/bagel.png'), localImageRatio: 1.3596 }),
    mk({ name: 'Confiture de fraise', emoji: '🍓', dlc: frDate(169), days_left: 169, localImage: require('../../assets/dev-preview-food/confiture-de-fraise.png'), localImageRatio: 1.1724 }),
    mk({ name: 'Beurre de cacahuète', emoji: '🥜', dlc: frDate(170), days_left: 170, localImage: require('../../assets/dev-preview-food/beurre-de-cacahuete.png'), localImageRatio: 1.2526 }),
    mk({ name: 'Jus de pomme',    emoji: '🍎', dlc: frDate(171), days_left: 171, localImage: require('../../assets/dev-preview-food/jus-de-pomme.png'), localImageRatio: 0.9064 }),
    mk({ name: "Jus d'ananas",    emoji: '🍍', dlc: frDate(172), days_left: 172, localImage: require('../../assets/dev-preview-food/jus-d-ananas.png'), localImageRatio: 0.9081 }),
    mk({ name: 'Céréales',        emoji: '🥣', dlc: frDate(173), days_left: 173, localImage: require('../../assets/dev-preview-food/cereales.png'), localImageRatio: 1.2667 }),
    mk({ name: 'Lasagnes',        emoji: '🍝', dlc: frDate(174), days_left: 174, localImage: require('../../assets/dev-preview-food/lasagnes.png'), localImageRatio: 1.5612 }),
    mk({ name: 'Pizza',           emoji: '🍕', dlc: frDate(175), days_left: 175, localImage: require('../../assets/dev-preview-food/pizza.png'), localImageRatio: 1.4536 }),
    mk({ name: 'Quiche lorraine', emoji: '🥧', dlc: frDate(176), days_left: 176, localImage: require('../../assets/dev-preview-food/quiche-lorraine.png'), localImageRatio: 1.3598 }),
    mk({ name: 'Sandwich jambon fromage', emoji: '🥪', dlc: frDate(177), days_left: 177, localImage: require('../../assets/dev-preview-food/sandwich-jambon-fromage.png'), localImageRatio: 1.8782 }),
    mk({ name: 'Salade de pâtes', emoji: '🍝', dlc: frDate(178), days_left: 178, localImage: require('../../assets/dev-preview-food/salade-de-pates.png'), localImageRatio: 1.2892 }),
    mk({ name: 'Riz au lait',     emoji: '🍮', dlc: frDate(179), days_left: 179, localImage: require('../../assets/dev-preview-food/riz-au-lait.png'), localImageRatio: 1.228 }),
    mk({ name: 'Potiron',         emoji: '🎃', dlc: frDate(180), days_left: 180, localImage: require('../../assets/dev-preview-food/potiron.png'), localImageRatio: 1.1866 }),
    mk({ name: 'Poireau',         emoji: '🌱', dlc: frDate(181), days_left: 181, localImage: require('../../assets/dev-preview-food/poireau.png'), localImageRatio: 1.4135 }),
    mk({ name: 'Betterave crue',  emoji: '🔴', dlc: frDate(182), days_left: 182, localImage: require('../../assets/dev-preview-food/betterave-crue.png'), localImageRatio: 1.3413 }),
    mk({ name: 'Navet',           emoji: '🥔', dlc: frDate(183), days_left: 183, localImage: require('../../assets/dev-preview-food/navet.png'), localImageRatio: 1.3636 }),
    mk({ name: 'Radis noir',      emoji: '⚫️', dlc: frDate(184), days_left: 184, localImage: require('../../assets/dev-preview-food/radis-noir.png'), localImageRatio: 1.4022 }),
    mk({ name: 'Panais',          emoji: '🥕', dlc: frDate(185), days_left: 185, localImage: require('../../assets/dev-preview-food/panais.png'), localImageRatio: 1.5304 }),
    mk({ name: 'Topinambour',     emoji: '🥔', dlc: frDate(186), days_left: 186, localImage: require('../../assets/dev-preview-food/topinambour.png'), localImageRatio: 1.7288 }),
    mk({ name: 'Chou rouge',      emoji: '🟣', dlc: frDate(187), days_left: 187, localImage: require('../../assets/dev-preview-food/chou-rouge.png'), localImageRatio: 1.5684 }),
    mk({ name: 'Chou blanc',      emoji: '🥬', dlc: frDate(188), days_left: 188, localImage: require('../../assets/dev-preview-food/chou-blanc.png'), localImageRatio: 1.4573 }),
    mk({ name: 'Chou frisé (kale)', emoji: '🥬', dlc: frDate(189), days_left: 189, localImage: require('../../assets/dev-preview-food/chou-frise-kale.png'), localImageRatio: 1.4663 }),
    mk({ name: 'Pak choï',        emoji: '🥬', dlc: frDate(190), days_left: 190, localImage: require('../../assets/dev-preview-food/pak-choi.png'), localImageRatio: 1.365 }),
    mk({ name: 'Tempeh',          emoji: '🟫', dlc: frDate(191), days_left: 191, localImage: require('../../assets/dev-preview-food/tempeh.png'), localImageRatio: 1.7613 }),
    mk({ name: 'Lentilles corail', emoji: '🟠', dlc: frDate(192), days_left: 192, localImage: require('../../assets/dev-preview-food/lentilles-corail.png'), localImageRatio: 1.7465 }),
    mk({ name: 'Pois cassés',     emoji: '🟢', dlc: frDate(193), days_left: 193, localImage: require('../../assets/dev-preview-food/pois-casses.png'), localImageRatio: 1.8286 }),
    mk({ name: 'Haricots blancs', emoji: '🫘', dlc: frDate(194), days_left: 194, localImage: require('../../assets/dev-preview-food/haricots-blancs.png'), localImageRatio: 1.7034 }),
    mk({ name: 'Pois chiches cuits', emoji: '🫘', dlc: frDate(195), days_left: 195, localImage: require('../../assets/dev-preview-food/pois-chiches-cuits.png'), localImageRatio: 1.723 }),
  ];
}
